<!-- Global stylesheets -->
<link rel="stylesheet" type="text/css" href="{BASE_URL}themes/{THEMES}/style/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{BASE_URL}themes/{THEMES}/style/css/plugins.css">
<link rel="stylesheet" type="text/css" href="{BASE_URL}themes/{THEMES}/style/revolution/css/settings.css">
<link rel="stylesheet" type="text/css" href="{BASE_URL}themes/{THEMES}/style/revolution/css/layers.css">
<link rel="stylesheet" type="text/css" href="{BASE_URL}themes/{THEMES}/style/revolution/css/navigation.css">
<link rel="stylesheet" type="text/css" href="{BASE_URL}themes/{THEMES}/style/type/icons.css">
<link rel="stylesheet" type="text/css" href="{BASE_URL}themes/{THEMES}/style.css">
<link rel="stylesheet" type="text/css" href="{BASE_URL}themes/{THEMES}/style/css/color/lavender.css">
<!-- /global stylesheets -->